### PR TITLE
Fixed an issue where remaining slipdays would not reach the frontend

### LINKED ISSUE #751: SetSlipDays are called from multiple places and on different types
Ideally, there should be fewer specific places to do this updating. Maybe it should only be done in the `database` package. Needs investigation.

### PR DESCRIPTION
**Pull request by JosteinLindhom**
Fixes #751.

### CODE REVIEW

File: database/gormdb_enrollment.go [hunk 1]
```diff
@@ -88,6 +88,12 @@ func (db *GormDB) getEnrollments(model interface{}, statuses ...qf.Enrollment_Us
 		Find(&enrollments); err != nil {
 		return nil, err
 	}
+	for _, enrollment := range enrollments {
+		if enrollment.GetCourse() == nil {
```
Comment (meling) [inline database/gormdb_enrollment.go:92]: I don't think this check is necessary. If it is necessary, we should move the check inside the `SetSlipDays` method, and simply return if the provided course is `nil`.
