### PR TITLE
Redesigned frontend

### LINKED ISSUE #569: Review.Ready bool field fails to reset
When trying to cycle the `Ready` field, the returned value will remain true, even if set to false.

Running the code in `TestCreateUpdateReview` shows the problem:
```go
	review.Score = 90
	review.Ready = true
	updateSubmission(t, db, review)

	review.Score = 50
	review.Ready = false
	updateSubmission(t, db, review)
```
After setting `Ready = true` and then setting it back to `false` it will remain `true`, even though the `Score = 50` was updated correctly.
```text
go test -v -run TestCreateUpdateReview
=== RUN   TestCreateUpdateReview
sub 2: false, score: 95
sub 2: true, score: 90
sub 2: true, score: 50
```
This is a known GORM problem; [this](https://stackoverflow.com/questions/56653423/gorm-doesnt-update-boolean-field-to-false) seems to provide a solution.

### PR DESCRIPTION
**Pull request by JosteinLindhom**
This pull request implements a redesigned frontend.

TODOs:

- [x] Manual Review
- [x] Release
- [x] Promote / Demote / Reject course members
- [x] Display more user information in the members view
- [x] Implement rebuild
- [ ] General visual improvements

This PR includes both the current and redesigned frontend. Running QuickFeed enables a user to visit both (given that both are webpacked), but the default is the current frontend.

Fixes #569.

### CODE REVIEW

File: dev/src/components/Members.tsx [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+
+    }
+
+    const approveAll = () => {
+        for (const enrollment of pending) {
+            actions.updateEnrollment({enrollment: enrollment, status: Enrollment.UserStatus.STUDENT})
+        }
+    }
+
+    if (!isTeacher(state.enrollmentsByCourseId[courseID])) {
```
Comment (meling) [inline dev/src/components/Members.tsx:39]: Add comment to explain this redirect.

File: dev/src/components/Members.tsx [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+    const sort = () => {
+        switch (func) {
+            case "STATUS":
+                return Enrollment.prototype.getStatus
+            case "ID":
+                return Enrollment.prototype.getId
+            default:
+                return Enrollment.prototype.getStatus
+        }
+
```
Comment (meling) [inline dev/src/components/Members.tsx:30]: Remove

File: dev/src/components/navbar/NavBarCourse.tsx [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+            <li onClick={() => { onCourseClick(enrollment) }}>
+                <div className="col" id="title">
+                    {enrollment.getCourse()?.getCode()}
+                </div>
+                <div className="col" title="icon">
+                    <i className={selected ? "icon fa fa-caret-down fa-lg float-right" : "icon fa fa-caret-down fa-rotate-90 fa-lg float-right"}></i>
+                </div>
+            </li>
+            <div className={selected ? Status.ActiveLab : Status.Inactive}>
+                {selected && enrollment.getStatus() === Enrollment.UserStatus.STUDENT ? <NavBarLabs /> : null}
```
Comment (meling) [inline dev/src/components/navbar/NavBarCourse.tsx:40]:
```tsx
                {selected && isStudent(enrollment) ? <NavBarLabs /> : null}
                {selected && isTeacher(enrollment) ? <NavBarTeacher /> : null}
```

File: dev/src/components/navbar/NavBarCourse.tsx [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+    const history = useHistory()
+    // If selected, used to show teacher / student navbar for that course
+    const selected = state.activeCourse === enrollment.getCourseid()
+
+    const onCourseClick = (enrollment: Enrollment) => {
+        if (selected) {
+            // Unselect the active course
+            actions.setActiveCourse(0)
+            history.push("/")
+        }
```
Comment (meling) [inline dev/src/components/navbar/NavBarCourse.tsx:21]: `} else {`

File: dev/src/components/navbar/NavBarCourse.tsx [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+import { Status } from "../../consts";
+import { useActions, useAppState } from "../../overmind";
+import NavBarLabs from "./NavBarLabs";
+import NavBarTeacher from "./NavBarTeacher";
+
+const NavBarCourse = ({ enrollment }: { enrollment: Enrollment }): JSX.Element => {
+    const state = useAppState()
+    const actions = useActions()
+    const history = useHistory()
+    // If selected, used to show teacher / student navbar for that course
```
Comment (meling) [inline dev/src/components/navbar/NavBarCourse.tsx:13]: I'm a bit confused by the comment and the `selected` variable. Can you clarify this comment. The code sets `selected` to true if the courseID of the passed-in enrollment equals the active course.

File: dev/src/components/navbar/NavBarFooter.tsx [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+            return (
+                <li hidden={hidden}>
+                    <Link to="/admin" className="Sidebar-items-link">
+                        Admin
+                    </Link>
+                </li>
+            )
+        }
+        return null
+
```
Comment (meling) [inline dev/src/components/navbar/NavBarFooter.tsx:61]: Remove

File: dev/src/components/forms/FormInput.tsx [hunk 7]
```diff
@@ -0,0 +1,22 @@
+import React from "react"
+
+
+
+const FormInput = ({ prepend, name, placeholder, defaultValue, onChange, type }: { prepend: string, name: string, placeholder?: string, defaultValue: string | undefined, onChange?: (e: React.FormEvent<HTMLInputElement>) => void, type?: string }): JSX.Element => {
```
Comment (meling) [inline dev/src/components/forms/FormInput.tsx:5]: Can this line be broken up to improve readability?

File: dev/src/components/admin/Users.tsx [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+
+
+const Users = (): JSX.Element => {
+    const state = useAppState()
+    const actions = useActions()
+
+    const headers: string[] = ["Name", "Email", "Student ID", "Role"]
+    const users = state.allUsers.map((user) => {
+        const data: (string | JSX.Element | CellElement)[] = []
+        data.push(
```
Comment (meling) [inline dev/src/components/admin/Users.tsx:17]: Doesn't seem to be necessary with a line break here.

File: dev/src/components/Statistics.tsx [hunk 9]
```diff
@@ -0,0 +1,11 @@
+import React from "react"
```
Comment (meling) [inline dev/src/components/Statistics.tsx:1]: Delete file for now. It is easy to start over

File: dev/src/components/Search.tsx [hunk 10]
```diff
@@ -0,0 +1,30 @@
+import React, { useEffect } from "react"
+import { useActions } from "../overmind"
+
+/** Search */
+/**
+ *  This component updates either the supplied query state, or the query in Overmind state
+ *  Used to determine if elements in the component it is in should be hidden or not.
```
Comment (meling) [inline dev/src/components/Search.tsx:7]: Couldn't quite get what the doc comment. Can you clarify it. Especially: `... if elements in the component it is in ...` was confusing.

File: dev/src/components/ReviewResult.tsx [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+                            <th scope="col">Status</th>
+                            <th scope="col">Comment</th>
+                        </tr>
+                    </thead>
+                    <tbody>
+                        {result}
+                    </tbody>
+                </table>
+            }
+
```
Comment (meling) [inline dev/src/components/ReviewResult.tsx:40]: Remove blank line

File: dev/src/components/Profile.tsx [hunk 12]
```diff
@@ -0,0 +1,55 @@
...
+                                {state.isValid ? null : <SignupText />}
+                            </ProfileForm>
+                        }
+                    </ProfileCard>
+                </div>
+            </div>
+        )
+    }
+    return <Redirect to="/" />
+
```
Comment (meling) [inline dev/src/components/Profile.tsx:51]: Remove blank lines

File: dev/src/components/Profile.tsx [hunk 13]
```diff
@@ -0,0 +1,55 @@
...
+            <div>
+                <div className="jumbotron">
+                    <div className="centerblock container">
+                        <h1>Hi, {state.self.getName()}</h1>
+                        You can edit your user information here.
+                    </div>
+                </div>
+                <div className="container">
+                    <ProfileCard>
+                        {!editing ?
```
Comment (meling) [inline dev/src/components/Profile.tsx:39]: Here you could swap the if and else part by using `editing` instead of `!editing`.

File: public/index.html [hunk 14]
```diff
@@ -27,7 +27,7 @@
         crossorigin="anonymous">
 
     <!-- Custom styles -->
-    <link rel="stylesheet" type="text/css" href="/styles/style.css">
+    <link rel="stylesheet" type="text/css" href="/static/styles/style.css">
```
Comment (meling) [inline public/index.html:30]: Just checking: is `/static` correct here? Since there are no actual directories with that name... I assume there is some rewrite going on.

File: dev/src/react-app-env.d.ts [hunk 15]
```diff
@@ -0,0 +1 @@
+/// <reference types="react-scripts" />
```
Comment (meling) [inline dev/src/react-app-env.d.ts:1]: Is this used/required?

**Review by meling — CHANGES_REQUESTED** [review]
Here is the first part of my review. I've covered 77 of 117 files. Will try to cover the remaining later this weekend or next week.

File: dev/README.md [hunk 16]
```diff
@@ -0,0 +1,21 @@
+
```
[the remark this answers is not in the document]
Comment (JosteinLindhom) [reply dev/README.md]: Deleted for now

File: dev/src/pages/TeacherPage.tsx [hunk 17]
```diff
@@ -0,0 +1,64 @@
...
+/* TeacherPage enables routes to be accessed by the teacher only, and displays an overview of the different features available to the teacher. */
+const TeacherPage = (): JSX.Element => {
+    const state = useAppState()
+    const courseID = getCourseID()
+    const grpc = useGrpc().grpcMan
+    const isAuthorizedTeacher = useActions().isAuthorizedTeacher
+    const history = useHistory()
+    const root = `/course/${courseID}`
+
+    const members = { title: "View Members", notification: state.pendingEnrollments.length > 0 ? { color: Color.YELLOW, text: "Pending enrollments" } : undefined, text: "View all students, and approve new enrollments.", buttonText: "Members", to: `${root}/members` }
```
[the remark this answers is not in the document]
Comment (meling) [reply dev/src/pages/TeacherPage.tsx:24]: And the rest like this:
```ts
    const results = { title: "View results", text: "View results for all students in the course.", buttonText: "Results", to: `${root}/results` }
    const assignments = { title: "Manage Assignments", text: "View and edit assignments.", buttonText: "Assignments", to: `${root}/assignments` }
    const updateAssignments = { title: "Update Course Assignments", text: "Fetch assignments from GitHub.", buttonText: "Update Assignments", onclick: () => grpc.updateAssignments(courseID) }
```

**Review by meling — CHANGES_REQUESTED** [review]

File: dev/src/App.tsx [hunk 18]
```diff
@@ -0,0 +1,86 @@
...
+        async function setup() {
+            await actions.fetchUserData()
+        }
+        // If the user is not logged in, fetch user data to initialize the app state.
+        if (!state.isLoggedIn) {
+            setup()
+        }
+    }, [])
+
+    // Update the state's Time object every 20 seconds.
```
Comment (meling) [inline dev/src/App.tsx:28]: Can remove if `state.timeNow` is removed.

File: dev/src/App.tsx [hunk 19]
```diff
@@ -0,0 +1,86 @@
...
+        <div>
+            <NavBar />
+            <div className="app wrapper">
+                <div id="content">
+                    {Main()}
+                </div>
+            </div>
+        </div>
+    )
+
```
Comment (meling) [inline dev/src/App.tsx:81]: Remove blank line

File: dev/src/Helpers.ts [hunk 20]
```diff
@@ -0,0 +1,226 @@
...
+export interface Deadline {
+    className: string,
+    message: string,
+    daysUntil: number,
+}
+
+/** Utility function for LandingpageTable functionality. To format the output string and class/css based on how far the deadline is in the future */
+// layoutTime = "2021-03-20T23:59:00"
+export const timeFormatter = (deadline: string, now: Date): Deadline => {
+    const timeToDeadline = new Date(deadline).getTime() - now.getTime()
```
Comment (meling) [inline dev/src/Helpers.ts:36]:
```ts
export const timeFormatter = (deadline: string): Deadline => {
    const timeToDeadline = new Date(deadline).getTime() - new Date().getTime()
```

File: dev/src/components/Groups.tsx [hunk 21]
```diff
@@ -0,0 +1,113 @@
...
+        return <td><span className="badge badge-info clickable" onClick={() => setEditing(group)}>Edit</span></td>
+    }
+
+    const GroupRow = ({ group }: { group: Group }) => {
+        return (
+            <>
+                <tr hidden={groupSearch(group)}>
+                    <th key={group.getId()}>
+                        {group.getName()}
+                        <span className="badge badge-warning ml-2">{group.getStatus() == Group.GroupStatus.PENDING ? "Pending" : null}</span>
```
Comment (meling) [inline dev/src/components/Groups.tsx:61]: Could add a helper for `isPendingGroup: group.getStatus() === Group.GroupStatus.PENDING`

File: dev/src/components/forms/CourseForm.tsx [hunk 22]
```diff
@@ -0,0 +1,156 @@
...
+                </form>
+            }
+        </div>
+
+    )
+}
+
+export default CourseForm
+
+// Helper functions for default values for new courses
```
Comment (meling) [inline dev/src/components/forms/CourseForm.tsx:149]: Move these helpers to other file or above so that the file ends with the export default.

**Review by meling — CHANGES_REQUESTED** [review]
Now is done...

File: dev/src/components/teacher/Assignments.tsx [hunk 23]
```diff
@@ -0,0 +1,89 @@
...
+import { getCourseID, isManuallyGraded, Color } from "../../Helpers"
+import { useActions, useAppState } from "../../overmind"
+import Button, { ButtonType } from "../admin/Button"
+import EditBenchmark from "./EditBenchmark"
+import EditCriterion from "./EditCriterion"
+
+
+// TODO: Needs some love. Currently a mess.
+
+const Assignments = (): JSX.Element => {
```
[the remark this answers is not in the document]
Comment (JosteinLindhom) [reply dev/src/components/teacher/Assignments.tsx:13]: This component displays all assignments for a given course and:
- for `!isManuallyGraded(assignment)` enables teachers to rebuild all submissions
- for manually graded assignments, allows teachers to add or remove criteria and benchmarks for the assignment

File: dev/src/components/teacher/EditCriterion.tsx [hunk 24]
```diff
@@ -0,0 +1,53 @@
+import React, { useState } from "react";
+import { Assignment, GradingCriterion } from "../../../proto/ag/ag_pb";
+import { useActions, useGrpc } from "../../overmind";
+
+
+
+const EditCriterion = ({ criterion, benchmarkID, assignment }: { criterion?: GradingCriterion, benchmarkID: number, assignment: Assignment }): JSX.Element => {
```
[the remark this answers is not in the document]
Comment (JosteinLindhom) [reply dev/src/components/teacher/EditCriterion.tsx:6]: It is needed for creating a new criterion for an assignmnent.

```ts
const c = criterion ?? new GradingCriterion().setBenchmarkid(benchmarkID)
```

File: dev/src/overmind/namespaces/review/actions.ts [hunk 25]
```diff
@@ -0,0 +1,42 @@
...
+export const setSelectedReview = ({ state }: Context, index: number): void => {
+    state.review.selectedReview = index
+}
+
+/* Update the selected review */
+export const updateReview = async ({ state, actions, effects }: Context): Promise<void> => {
+    // If canUpdate is false, the review cannot be updated
+    if (state.review.canUpdate) {
+        const response = await effects.grpcMan.updateReview(json((state.review.currentReview as Review)), state.activeCourse)
+        if (success(response) && response.data) {
```
[the remark this answers is not in the document]
Comment (JosteinLindhom) [reply dev/src/overmind/namespaces/review/actions.ts:16]: I don't think so

File: dev/src/components/navbar/NavBarTeacher.tsx [hunk 26]
```diff
@@ -0,0 +1,22 @@
+import React from "react"
+import { useAppState } from "../../overmind"
+import NavBarLink, { NavLink } from "./NavBarLink"
+
+
```
[the remark this answers is not in the document]
Comment (JosteinLindhom) [reply dev/src/components/navbar/NavBarTeacher.tsx:5]: I like the two lines between imports and first const function. Do you have a suggestion on how to handle this in files such as `DynamicTable.tsx`, where types and functions are defined? Perhaps those could go in a separate files, `consts` and `Helpers`.

[the remark this answers is not in the document]
Comment (meling) [reply dev/src/components/navbar/NavBarTeacher.tsx:5]: If something is only useful to the rest of `DynamicTable.tsx`, then that's right place for such types and functions are defined. If more generally applicable, then global files such as `consts` and `Helpers` are appropriate. If you prefer, it is also okay to have two blank lines between definitions as well, but in Go, the `gofmt` enforces only a single line between functions for example. The most important thing is to be consistent throughout the codebase.

File: dev/src/components/CourseCard.tsx [hunk 27]
```diff
@@ -43,10 +42,10 @@ const CourseCard = ({ course, enrollment }: CardProps): JSX.Element => {
                     <h5 className="card-title">{course.getName()} - {course.getTag()}/{course.getYear()}</h5>
                     {hasNone(status) ?
                         <div className="btn btn-primary course-button" onClick={() => actions.enroll(course.getId())}>Enroll</div>
-                    : hasPending(status) ?
-                        <div className="btn btn-secondary course-button disabled">Pending</div>
-                    :
-                        <div className="btn btn-primary course-button" onClick={() => history.push("/course/" + enrollment.getCourseid())}>Go to Course</div>
+                        : hasPending(status) ?
```
Comment (meling) [inline dev/src/components/CourseCard.tsx:45]: Maybe the `?` and `:` could be moved first on each line, including the one after `hasNone(status)` so that it (hopefully) becomes a little easier to see where the different parts of the if-else construction.

File: dev/src/components/Lab.tsx [hunk 28]
```diff
@@ -14,11 +12,8 @@ interface MatchProps {
     lab: string
 }
 
-
-
-/** Displays a Lab submission based on the /course/:id/:lab route
- *
- *  If used to display a lab for grading purposes, pass in a TeacherLab object
+/** Lab displays a submission based on the /course/:id/:lab route if the user is a student.
+ *  If the user is a teacher, Lab displays a submission based on the submission in state.currentSubmission.
```
Comment (meling) [inline dev/src/components/Lab.tsx:16]: I think it is enough to just say:
```
If the user is a teacher, Lab displays the state.currentSubmission.
```

File: dev/src/Helpers.ts [hunk 29]
```diff
@@ -231,6 +233,36 @@ export const defaultYear = (date: Date): number => {
     return (date.getMonth() <= 11 && date.getDate() <= 31) && date.getMonth() > 10 ? (date.getFullYear() + 1) : date.getFullYear()
 }
 
+export const generateSubmissionRows = (links: UserCourseSubmissions[], cellGenerator: (s: SubmissionLink) => RowElement, groupName?: boolean): Row[] => {
```
Comment (meling) [inline dev/src/Helpers.ts:236]: Maybe these would fit better in `DynamicTable.tsx`?

File: dev/src/components/Results.tsx [hunk 30]
```diff
@@ -47,25 +43,16 @@ const Results = (): JSX.Element => {
...
-            data.push(link.enrollment.hasGroup() ? (link.enrollment.getGroup() as Group)?.getName() : "")
-            if (link.submissions) {
-                for (const submissionLink of link.submissions) {
-                    data.push(getSubmissionCell(submissionLink))
-                }
-            }
-        }
-        return data
-    })
+    const base = groupView ? ["Name"] : ["Name", "Group"]
```
Comment (meling) [inline dev/src/components/Results.tsx:46]: Shouldn't the `groupView === true` lead to `["Name", "Group"]`? Looks like the opposite is the case now.

File: dev/src/components/ReviewPage.tsx [hunk 31]
```diff
@@ -41,26 +43,22 @@ const ReviewPage = (): JSX.Element => {
...
-        if (link.submissions && link.user) {
-            row.push({ value: link.user.getName(), link: `https://github.com/${link.user.getLogin()}` })
-            link.submissions.forEach(submission => {
-                row.push(generateReviewCell(submission))
-            })
-        }
-        return row
-    })
+    const links = groupView ? state.courseGroupSubmissions[courseID] : state.courseSubmissions[courseID]
+    const rows = generateSubmissionRows(links, generateReviewCell)
```
Comment (meling) [inline dev/src/components/ReviewPage.tsx:47]: In `Results.tsx` it has an extra `true` argument; should that be done here also?: (Didn't check the logic, just noticed the difference.)
```ts
const results = generateSubmissionRows(links, getSubmissionCell, true)
```

File: dev/src/overmind/actions.tsx [hunk 32]
```diff
@@ -143,8 +143,15 @@ export const updateSubmission = async ({ state, effects }: Context, status: Subm
         return
     }
 
+    if (state.activeSubmissionLink?.getAssignment()?.getIsgrouplab()) {
+        actions.loopThroughAndUpdate({ links: state.courseGroupSubmissions[state.activeCourse], status: status })
+    }
+    actions.loopThroughAndUpdate({ links: state.courseSubmissions[state.activeCourse], status: status })
+}
+
+export const loopThroughAndUpdate = ({ state }: Context, { links, status }: { links: UserCourseSubmissions[], status: Submission.Status }): void => {
```
Comment (meling) [inline dev/src/overmind/actions.tsx:152]: Rename this; too generic name. What about: `updateCurrentSubmissionStatus`??

File: dev/src/overmind/actions.tsx [hunk 33]
```diff
@@ -143,8 +143,15 @@ export const updateSubmission = async ({ state, effects }: Context, status: Subm
         return
     }
 
+    if (state.activeSubmissionLink?.getAssignment()?.getIsgrouplab()) {
+        actions.loopThroughAndUpdate({ links: state.courseGroupSubmissions[state.activeCourse], status: status })
+    }
+    actions.loopThroughAndUpdate({ links: state.courseSubmissions[state.activeCourse], status: status })
```
Comment (meling) [inline dev/src/overmind/actions.tsx:149]: Should this be called both inside the for loop and here? That is, should it be called twice if the if-condition is satisfied?

File: dev/src/overmind/actions.tsx [hunk 34]
```diff
@@ -557,14 +573,14 @@ export const fetchUserData = async ({ state, actions }: Context): Promise<boolea
 
 /** Switches between teacher and student view. */
 export const changeView = async ({ state, effects }: Context, courseID: number): Promise<void> => {
-    const enrollment = state.enrollmentsByCourseID[courseID]
-    if (isStudent(enrollment)) {
+    const enrollmentStatus = state.enrollmentsByCourseID[courseID].getStatus()
```
Comment (meling) [inline dev/src/overmind/actions.tsx:584]: Just wondering if there is a reason to get the status and check that instead of just doing as before using the `isStudent` on the `enrollment` instead??

Maybe then you can reuse the `enrollment` variable to set the status as well?? Or maybe I'm missing something about typescript variables.

```tsx
    const enrollment = state.enrollmentsByCourseID[courseID]
    if (isStudent(enrollment)) {
        const status = await effects.grpcMan.getEnrollmentsByUser(state.self.getId(), [Enrollment.UserStatus.TEACHER])
        if (status.data?.getEnrollmentsList().find(enrollment => enrollment.getCourseid() == courseID)) {
            enrollment.setStatus(Enrollment.UserStatus.TEACHER)
        }
    }
    if (isTeacher(enrollment)) {
        enrollment.setStatus(Enrollment.UserStatus.STUDENT)
```

Comment (meling) [reply dev/src/overmind/actions.tsx:584]: Or maybe `enrollment` here should be changed to `enroll` to avoid confusion between the two enrollment variables:
```ts
        if (status.data?.getEnrollmentsList().find(enroll => enroll.getCourseid() == courseID)) {
```

Comment (JosteinLindhom) [reply dev/src/overmind/actions.tsx:584]: Not quite sure why, but doing it like you suggest above, and earlier, prevent the UI from rerendering after changing view once.

File: dev/src/overmind/actions.tsx (hunk 33 above)
Comment (JosteinLindhom) [reply dev/src/overmind/actions.tsx:149]: Currently `state.GroupSubmissions` and `state.courseSubmissions` are two separate lists. 

I added a button to switch between group view and student view in review and results. Where group view lists submissions by group, while student view lists submissions by user. 

When updating a group submission I want both lists to reflect the updated status. This way, when you update status of a submission in student view, the submission will also have the updated status if you switch to group view.

File: dev/src/components/Results.tsx (hunk 30 above)
Comment (JosteinLindhom) [reply dev/src/components/Results.tsx:46]: When `groupView === true`, the `Name` column will contain the group name rather than student name, hence `"Group"`, which displayed the group name, is not needed.

Group view:
image

Student (individual) view:
image

File: dev/src/overmind/actions.tsx (hunk 33 above)
Comment (meling) [reply dev/src/overmind/actions.tsx:149]: I now see they aren't identical. Resolving.

File: dev/src/overmind/actions.tsx (hunk 34 above)
Comment (meling) [reply dev/src/overmind/actions.tsx:584]: ok. Resolving
