### PR TITLE
Check for uninitialized order field

### LINKED ISSUE #999: Fetching multiple new assignments from tests generates a single assignment
Three separate `assignment.yml` files were added to a `tests` repository.
These had the deprecated `assignmentid` field. As a consequence, no assignments were generated by QuickFeed.
When a fix was pushed, only one of the three assignments was generated by QuickFeed.

```
DAT240/tests
|__ Lab1
|   |_ assignment.yml
|
|__ Lab2
|   |_ assignment.yml
|
|__ Lab3
|   |_ assignment.yml
```

Lab1 was added when the push event with the fix was received.
Lab 2 and 3 were added when I invoked `UpdateAssignments` two times, once for each assignment.

I expected all three to be added when the push event was received.

Additional information:

Logs from first commit to `tests`:

```
"added": [
      ...
      "Lab1/assignment.yml",
      ...
      "Lab2/assignment.yml",
      ...
      "Lab3/assignment.yml",
      ...
    ]

...

2023-08-20T21:04:11.202+0200    DEBUG   hooks/push.go:36        For course(1)=Advanced Programming
2023-08-20T21:04:11.202+0200    DEBUG   assignments/assignments.go:36   Updating DAT240 from 'tests' repository
2023-08-20T21:04:11.445+0200    DEBUG   scm/fetcher.go:50       Clone(https://github.com/dat240-2023/tests.git)
2023-08-20T21:04:11.915+0200    DEBUG   scm/fetcher.go:63       CloneDir = /home/quickfeed/courses/dat240-2023/tests
2023-08-20T21:04:11.915+0200    DEBUG   assignments/assignments.go:49   Successfully cloned tests repository to: /home/quickfeed/courses/dat240-2023/tests
2023-08-20T21:04:11.916+0200    DEBUG   assignments/assignments.go:74   Failed to update database for: CourseID:1  name:"Lab1"  deadline:{seconds:1694131140}  scoreLimit:90
2023-08-20T21:04:11.916+0200    DEBUG   assignments/assignments.go:74   Failed to update database for: CourseID:1  name:"Lab2"  deadline:{seconds:1695945540}  scoreLimit:100
2023-08-20T21:04:11.916+0200    DEBUG   assignments/assignments.go:74   Failed to update database for: CourseID:1  name:"Lab3"  deadline:{seconds:1697759940}  scoreLimit:100
2023-08-20T21:04:11.916+0200    ERROR   assignments/assignments.go:76   Failed to update assignments in database: record not found
```

Logs from when a fix was pushed & `UpdateAssignments` invoked:

```
    "modified": [
      "Lab1/assignment.yml",
      "Lab2/assignment.yml",
      "Lab3/assignment.yml"
    ]

2023-08-23T00:00:57.767+0200    DEBUG   hooks/push.go:36        For course(1)=Advanced Programming
2023-08-23T00:00:57.767+0200    DEBUG   assignments/assignments.go:36   Updating DAT240 from 'tests' repository
2023-08-23T00:00:58.007+0200    DEBUG   scm/fetcher.go:33       Pulling(https://github.com/dat240-2023/tests.git)
2023-08-23T00:00:58.492+0200    DEBUG   assignments/assignments.go:49   Successfully cloned tests repository to: /home/quickfeed/courses/dat240-2023/tests
2023-08-23T00:00:58.506+0200    DEBUG   assignments/assignments.go:79   Assignments for DAT240 successfully updated from 'tests' repo
2023-08-23T00:01:07.069+0200    DEBUG   web/quickfeed_service.go:354    GetSubmissions: &{CourseID:1  UserID:1 {0 /qf.QuickFeedService/GetSubmissions false} map[Accept:[*/*] Accept-Encoding:[gzip, deflate, br>
2023-08-23T00:01:07.071+0200    DEBUG   web/quickfeed_service.go:354    GetSubmissions: &{CourseID:2  UserID:1 {0 /qf.QuickFeedService/GetSubmissions false} map[Accept:[*/*] Accept-Encoding:[gzip, deflate, br>
2023-08-23T00:01:07.073+0200    DEBUG   web/access_control.go:26        (user=1, course=1) has enrollment status TEACHER
2023-08-23T00:01:07.074+0200    DEBUG   web/access_control.go:26        (user=1, course=2) has enrollment status TEACHER
2023-08-23T00:01:09.759+0200    DEBUG   web/quickfeed_service.go:373    GetSubmissionsByCourse: &{CourseID:1  Type:USER {0 /qf.QuickFeedService/GetSubmissionsByCourse false} map[Accept:[*/*] Accept-Encoding:[>
2023-08-23T00:01:09.788+0200    DEBUG   web/quickfeed_service.go:373    GetSubmissionsByCourse: &{CourseID:1  Type:GROUP {0 /qf.QuickFeedService/GetSubmissionsByCourse false} map[Accept:[*/*] Accept-Encoding:>
2023-08-23T00:09:20.948+0200    DEBUG   assignments/assignments.go:36   Updating DAT320 from 'tests' repository
2023-08-23T00:09:21.216+0200    DEBUG   scm/fetcher.go:33       Pulling(https://github.com/dat320-2023/tests.git)
2023-08-23T00:09:21.470+0200    DEBUG   assignments/assignments.go:49   Successfully cloned tests repository to: /home/quickfeed/courses/dat320-2023/tests
2023-08-23T00:09:21.482+0200    DEBUG   assignments/assignments.go:79   Assignments for DAT320 successfully updated from 'tests' repo
2023-08-23T00:09:21.643+0200    DEBUG   scm/fetcher.go:33       Pulling(https://github.com/dat320-2023/assignments.git)
2023-08-23T00:09:21.849+0200    DEBUG   web/quickfeed_service.go:533    Successfully cloned assignments repository to: /home/quickfeed/courses/dat320-2023/assignments
2023-08-23T00:09:51.874+0200    DEBUG   assignments/assignments.go:36   Updating DAT240 from 'tests' repository
2023-08-23T00:09:52.073+0200    DEBUG   scm/fetcher.go:33       Pulling(https://github.com/dat240-2023/tests.git)
2023-08-23T00:09:52.291+0200    DEBUG   assignments/assignments.go:49   Successfully cloned tests repository to: /home/quickfeed/courses/dat240-2023/tests
2023-08-23T00:09:52.301+0200    DEBUG   assignments/assignments.go:79   Assignments for DAT240 successfully updated from 'tests' repo
```

### PR DESCRIPTION
**Pull request by meling**
This should produce error log if the order field wasn't initialized in the assignment.yml file.

Fixes #999

### CODE REVIEW

File: assignments/assignments_parser_test.go [hunk 1]
```diff
@@ -216,6 +221,93 @@ func TestParseUnknownFields(t *testing.T) {
...
+	}
+
+	// Save the assignments to the database
+	if err := db.UpdateAssignments(assignments); err != nil {
+		t.Fatal(err)
+	}
+
+	// Read the assignments from the database
+	gotAssignments, err := db.GetAssignmentsByCourse(course.ID)
+
```
Comment (meling) [inline assignments/assignments_parser_test.go:263]: Remove the blank line. We try to keep the error checked right after the line that returned the `err`. (This applies to several cases below as well.)

PS: My VSCode Go extension configuration automatically fixes these types of things for me via the `gofumpt` formatter.

File: assignments/assignments_parser_test.go [hunk 2]
```diff
@@ -216,6 +221,93 @@ func TestParseUnknownFields(t *testing.T) {
...
+	}
+
+	// Read the assignments from the database
+	gotNewAssignments, err := db.GetAssignmentsByCourse(course.ID)
+
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	// Should be 3 assignments now
```
Comment (meling) [inline assignments/assignments_parser_test.go:299]: ... assignments in the database now

File: assignments/assignments_parser_test.go [hunk 3]
```diff
@@ -216,6 +221,93 @@ func TestParseUnknownFields(t *testing.T) {
...
+	if len(gotNewAssignments) != 3 {
+		t.Errorf("len(assignments) = %d, want %d", len(gotNewAssignments), 3)
+	}
+
+	// Check that the new assignments are the same as the ones we parsed
+	if diff := cmp.Diff(newAssignments, gotNewAssignments, protocmp.Transform()); diff != "" {
+		t.Errorf("readTestsRepositoryContent() mismatch (-want +got):\n%s", diff)
+	}
+
```
Comment (meling) [inline assignments/assignments_parser_test.go:308]: Remove blank line

File: assignments/assignments_parser_test.go [hunk 4]
```diff
@@ -216,6 +221,93 @@ func TestParseUnknownFields(t *testing.T) {
 	}
 }
 
+func TestParseAndSaveAssignment(t *testing.T) {
```
Comment (meling) [inline assignments/assignments_parser_test.go:224]: This is an excellent test for the expected case. I think we are still missing the bad case, similar to the example you explained in #999. 

Right now, I think `readTestsRepositoryContent` will return an error if a single `yaml` file has a mistake we don't tolerate, e.g., using `assignmentid` instead of `order`. Thus, I don't think we will be able to test the `db.UpdateAssignments` with one or more faulty assignments. That said, such a test should probably be done in the `database` package if we actually need it and perhaps in a separate PR. What's your take?
