### PR TITLE
bug(manifest): Creating a GitHub App using our manifest panics when served on local IP

### LINKED ISSUE #1176: bug(manifest): Creating a GitHub App using our manifest panics when served on local IP
```
$ quickfeed -dev -new
2025/01/07 22:33:10 Loading environment variables from /home/jostein/code/quickfeed/.env
2025/01/07 22:33:10 Starting QuickFeed on 192.168.109.185:443
2025/01/07 22:33:10 Existing credentials successfully loaded.
2025/01/07 22:33:10 Important: The GitHub user that installs the QuickFeed App will become the server's admin user.
2025/01/07 22:33:10 Go to https://192.168.109.185/manifest to install the QuickFeed GitHub App.
2025/01/07 22:33:11 http: TLS handshake error from 192.168.96.1:58505: remote error: tls: unknown certificate
2025/01/07 22:33:11 http: TLS handshake error from 192.168.96.1:58506: remote error: tls: unknown certificate
2025/01/07 22:33:11 http: TLS handshake error from 192.168.96.1:58507: remote error: tls: unknown certificate
<nil>
2025/01/07 22:33:17 http2: panic serving 192.168.96.1:58508: runtime error: invalid memory address or nil pointer dereference
goroutine 46 [running]:
net/http.(*http2serverConn).runHandler.func1()
        /usr/local/go/src/net/http/h2_bundle.go:6242 +0x145
panic({0x106c8c0?, 0x1b68a40?})
        /usr/local/go/src/runtime/panic.go:785 +0x132
github.com/quickfeed/quickfeed/web/manifest.New.(*Manifest).conversion.func1({0x13caae0, 0xc000122000}, 0x0?)
        /home/jostein/code/quickfeed/web/manifest/manifest.go:161 +0x532
net/http.HandlerFunc.ServeHTTP(0xc0000dc1c0?, {0x13caae0?, 0xc000122000?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x0?, {0x13caae0, 0xc000122000}, 0xc000220640)
        /usr/local/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0x0?}, {0x13caae0?, 0xc000122000?}, 0x0?)
        /usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.initALPNRequest.ServeHTTP({{0x13cc538?, 0xc0005302d0?}, 0xc0003ec388?, {0xc0004b21e0?}}, {0x13caae0, 0xc000122000}, 0xc000220640)
        /usr/local/go/src/net/http/server.go:3819 +0x231
net/http.(*http2serverConn).runHandler(0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/net/http/h2_bundle.go:6249 +0xf5
created by net/http.(*http2serverConn).scheduleHandler in goroutine 66
        /usr/local/go/src/net/http/h2_bundle.go:6183 +0x21d
2025/01/07 22:33:17 Loading environment variables from /home/jostein/code/quickfeed/.env
2025/01/07 22:33:17 missing application ID for provider github
```

### PR DESCRIPTION
**Pull request by JosteinLindhom**
- **bug(manifest): Creating a GitHub App using our manifest panics when served on local IP Fixes #1176**

The QuickFeed server would crash when trying to save the received `WebhookSecret` if the server runs on a private address.
This is because we do not support (i.e., do not request) webhooks when run on a private address.

This is fixed by verifying that we actually received a secret before trying to save it.

### CODE REVIEW

File: web/manifest/manifest.go [hunk 1]
```diff
@@ -153,11 +153,16 @@ func (m *Manifest) conversion() http.HandlerFunc {
...
 		envToUpdate := map[string]string{
-			appID:         strconv.FormatInt(*config.ID, 10),
-			appKey:        appKeyFile,
-			clientID:      *config.ClientID,
-			clientSecret:  *config.ClientSecret,
-			webhookSecret: *config.WebhookSecret,
+			appID:        strconv.FormatInt(*config.ID, 10),
+			appKey:       appKeyFile,
+			clientID:     *config.ClientID,
+			clientSecret: *config.ClientSecret,
```
Comment (meling) [inline web/manifest/manifest.go:159]: Actually, this should be changed to this:
```go
clientID:      config.GetClientID(),
clientSecret:  config.GetClientSecret(),
webhookSecret: config.GetWebhookSecret(),
```
This should avoid having to check for `nil` since it returns `""` when `nil`.

Comment (meling) [reply web/manifest/manifest.go:159]: And while already touching this file, we should fix these:
```go
if err := os.WriteFile(appKeyFile, []byte(config.GetPEM()), 0o600); err != nil {
```
```go
appID:         strconv.FormatInt(config.GetID(), 10),
```
```go
	log.Printf("Successfully created the %s GitHub App.", config.GetName())

	data := struct {
		Name string
	}{
		Name: config.GetName(),
	}
```
```go
	if err := env.Save(publicEnvFile, map[string]string{
		"QUICKFEED_APP_URL": config.GetHTMLURL(),
	}); err != nil {
		return err
	}
	log.Printf("App URL saved in %s: %s", publicEnvFile, config.GetHTMLURL())
```

**Comment by meling** [comment]
@JosteinLindhom could you fix the deep source issue and see if it would be possible to shut up codecov by adding some tests?

File: web/manifest/manifest.go [hunk 2]
```diff
@@ -63,13 +63,17 @@ type Manifest struct {
 	envFile string
 	handler http.Handler
 	done    chan error
+	client  *github.Client // optional, for testing
+	compile bool
```
Comment (meling) [inline web/manifest/manifest.go:67]: Rename `compile` to `runWebpack` or something more descriptive and add comment:
```go
runWebpack bool  // run webpack only for production
```

File: web/manifest/manifest_internal_test.go [hunk 3]
```diff
@@ -64,3 +74,140 @@ func TestForm(t *testing.T) {
...
+		},
+		"3": {
+			Name:         qtest.Ptr("test"),
+			ID:           qtest.Ptr(int64(123)),
+			ClientID:     qtest.Ptr("some-id"),
+			ClientSecret: qtest.Ptr("some-other-secret"),
+			HTMLURL:      qtest.Ptr("https://another-example.com"),
+			PEM:          qtest.Ptr("super-secret"),
+		},
+		// TODO: Test with webhook config (manifest with non-private address)
```
Comment (meling) [inline web/manifest/manifest_internal_test.go:148]: Is it easy to add?

File: web/manifest/manifest_internal_test.go [hunk 4]
```diff
@@ -64,3 +74,140 @@ func TestForm(t *testing.T) {
...
+	}
+
+	scmClient := scm.NewMockedGithubSCMClient(qtest.Logger(t), scm.WithMockAppConfig(config))
+	manifest := Manifest{
+		domain:  "localhost",
+		client:  scmClient.Client(),
+		envFile: "testdata/test.env",
+		done:    make(chan error, 1),
+		compile: false,
```
Comment (meling) [inline web/manifest/manifest_internal_test.go:157]: Add comment to explain that we don't want to run webpack for tests.

**Review by meling — CHANGES_REQUESTED** [review]
Mostly small things remaining on this one... Let's get it merged ;-)
